name = "ItemResponseRecipes"
uuid = "05da4de1-0d5c-4141-b8ea-157f25fdd429"
authors = ["Philipp Gewessler"]
version = "0.1.0"

[deps]
AbstractItemResponseModels = "0ab3451c-659c-47cd-a7a9-a2d579e209dd"
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[compat]
AbstractItemResponseModels = "0.1"
Colors = "0.12"
Makie = "0.18"
StatsBase = "0.33"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
VisualRegressionTests = "34922c18-7c2a-561c-bac1-01e79b2c4c92"

[targets]
test = ["Test", "VisualRegressionTests"]
